AWSTemplateFormatVersion: '2010-09-09'
Description: TetraForce API
Parameters:
  environment:
    Type: String
    Description: Name of the environment to use in naming.
    Default: production
  ApiId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/tetraforce/api/id'
  DeploymentBucket:
    Description: S3 Bucket used in CloudFormation deployment.
    Type: String
  release:
    Type: String
    Description: Name of the release name of the stack version to use.
    Default: production
  LambdaRole:
    Type: String
    Description: Arn of Lambda role assumed by fucntion.

Resources:
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiId
      AutoDeploy: 'true'
      StageName: !Ref environment

  GetTasksLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Sub "${release}/lambda/get_tasks.zip"
      Role: !Ref LambdaRole
      FunctionName: !Sub "TetraForce-Api-${environment}"
      Description: Lambda that returns ECS task information
      MemorySize: 128
      Timeout: 10