AWSTemplateFormatVersion: '2010-09-09'
Description: TetraForce API
Parameters:
  environment:
    Type: String
    Description: Name of the environment to use in naming.
    Default: production
  DeploymentBucket:
    Description: S3 Bucket used in CloudFormation deployment.
    Type: String
  release:
    Type: String
    Description: Name of the release name of the stack version to use.
    Default: production
  LambdaRole:
    Type: String
    Description: Arn of Lambda role assumed by fucntion.
  EcsCluster:
    Type: String
    Description: Name of ECS cluster connected to lambda functions
  TaskDefinition:
    Type: String
    Description: Name of the task definition to use with lambda functions

Resources:

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Description: Backend API for managing TetraForce game servers/tasks
      Name: !Sub "TetraForce-API-${environment}"
      ProtocolType: HTTP


  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      AutoDeploy: 'true'
      StageName: "$default"


  # =========
  # GET TASKS
  # =========
  GetTasksLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Sub "${release}/lambda/get_tasks.zip"
      Role: !Ref LambdaRole
      FunctionName: !Sub "TetraForce-Api-GetTasks-${environment}"
      Description: Lambda that returns ECS task information
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          CLUSTER: !Ref EcsCluster
  # Grant permission to API Gateway
  GetTasksLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*"
      FunctionName: !GetAtt GetTasksLambda.Arn
  # Create API Integration
  GetTasksIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties: 
      ApiId: !Ref HttpApi
      Description: !Sub "Integration for Get Tasks Lambda ${environment} for environment"
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !GetAtt GetTasksLambda.Arn
  # Create Api Route
  GetTasksRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties: 
      ApiId: !Ref HttpApi
      RouteKey: "GET /get_tasks"
      Target: !Sub "integrations/${GetTasksIntegration}"

  # ============
  # CREATE TASKS
  # ============
  CreateTaskLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Sub "${release}/lambda/create_task.zip"
      Role: !Ref LambdaRole
      FunctionName: !Sub "TetraForce-Api-CreateTask-${environment}"
      Description: Lambda that returns newly created ecs task
      MemorySize: 128
      Timeout: 120
      Environment:
        Variables:
          CLUSTER: !Ref EcsCluster
          TASK_DEFINITION: !Ref TaskDefinition
  # Grant permission to API Gateway
  CreateTaskLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*"
      FunctionName: !GetAtt CreateTaskLambda.Arn
  # Create API Integration
  CreateTaskIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties: 
      ApiId: !Ref HttpApi
      Description: !Sub "Integration for Create Task Lambda ${environment} for environment"
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !GetAtt CreateTaskLambda.Arn
  # Create Api Route
  CreateTaskRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties: 
      ApiId: !Ref HttpApi
      RouteKey: "GET /create_task"
      Target: !Sub "integrations/${CreateTaskIntegration}"

  # ==========
  # STOP TASKS
  # ==========
  StopTaskLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Sub "${release}/lambda/stop_task.zip"
      Role: !Ref LambdaRole
      FunctionName: !Sub "TetraForce-Api-StopTask-${environment}"
      Description: Lambda that stops an ecs task
      MemorySize: 128
      Timeout: 120
      Environment:
        Variables:
          CLUSTER: !Ref EcsCluster
  # Grant permission to API Gateway
  StopTaskLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*"
      FunctionName: !GetAtt StopTaskLambda.Arn
  # Create API Integration
  StopTaskIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties: 
      ApiId: !Ref HttpApi
      Description: !Sub "Integration for Stop Task Lambda ${environment} for environment"
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !GetAtt StopTaskLambda.Arn
  # Create Api Route
  StopTaskRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties: 
      ApiId: !Ref HttpApi
      RouteKey: "GET /stop_task"
      Target: !Sub "integrations/${StopTaskIntegration}"