AWSTemplateFormatVersion: '2010-09-09'
Description: TetraForce ECS Task
Parameters:
  LogGroupName:
    Type: String
    Description: The AWS CloudWatch log group to output logs to.
    Default: "/ecs/tetraforce"

  environment:
    Type: String
    Description: Name of the environment to use in naming.
    Default: production

  DockerTag:
    Description: Tag in DockerHub to deploy
    Type: String
    Default: "latest"

  DockerRepoSecret:
    Description: Arn of secret in AWS Secrets Manager holding Docker repo credentials
    Type: String
  
  TaskExecutionRole:
    Description: IAM Role used by ECS Tasks
    Type: String

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "${LogGroupName}/${environment}"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !Ref TaskExecutionRole
      Family: !Sub "TetraForce-${environment}"
      ContainerDefinitions:
      - Name: game_server
        Essential: 'true'
        Image: !Sub "docker.pkg.github.com/fornclake/tetraforce/tetraforce:${DockerTag}"
        RepositoryCredentials:
          CredentialsParameter: !Ref DockerRepoSecret
        MemoryReservation: 250
        PortMappings:
        - HostPort: 0
          ContainerPort: 7777
          Protocol: udp
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region:
              Ref: AWS::Region
            awslogs-group:
              Ref: LogGroup
Outputs:
  TaskArn:
    Description: ARN of the TaskDefinition
    Value: !Ref TaskDefinition