
AWSTemplateFormatVersion: '2010-09-09'
Description: TetraForce ECS Infrastructure
Parameters:
  #------------------------
  # Deployment Information
  #------------------------
  environment:
    Type: String
    Description: Name of the environment to use in naming.
    Default: production
  release:
    Type: String
    Description: Name of the release name of the stack version to use.
    Default: production
    AllowedValues: ['develop', 'stage', 'production']
    ConstraintDescription: "Must be a possible release version."
  DeploymentBucket:
    Default: tetraforce-deployment-bucket-us-east-2
    Description: S3 Bucket used in CloudFormation deployment
    Type: String
  AsgDesiredCapacity:
    Type: Number
    Default: 1
  DockerTag:
    Description: Tag in DockerHub to deploy
    Type: String
    Default: "latest"
  GitHubTokenSecret:
    Description: Arn of secret in AWS Secrets Manager holding GitHub credentials
    Type: String

  #------------
  # Networking
  #------------
  VpcId:
    Description: ID of the VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: The public subnets for the ALB to run in. (Space seperated)
    Type: String

  #------------
  # CloudWatch
  #------------
  LogGroup:
    Type: String
    Description: The AWS CloudWatch log group to output logs to.
    Default: "/ecs/tetraforce"

  #------------
  # Environment
  #------------
  MaxServerCount:
    Description: Max numbers of ECS tasks that can run in the cluster
    Type: String
    Default: "2"

Resources:

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${DeploymentBucket}/${release}/cloudformation/tetraforce/iam.yaml'
      Parameters:
        environment: !Ref environment
        DockerRepoSecret: !Ref GitHubTokenSecret
        ServerlistTable: !GetAtt Persistence.Outputs.ServerlistTable

  FargateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "TetraForce-${environment}"

  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "TetraForce-${environment}-task"
      GroupDescription: Opens port 7777 to world!
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - Description: Opens game server port
        CidrIp: 0.0.0.0/0
        FromPort: 7777
        ToPort: 7777
        IpProtocol: tcp

  TaskDefinition:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${DeploymentBucket}/${release}/cloudformation/tetraforce/task.yaml'
      Parameters:
        environment: !Ref environment
        LogGroupName: !Ref LogGroup
        DockerTag: !Ref DockerTag
        DockerRepoSecret: !Ref GitHubTokenSecret
        TaskExecutionRole: !GetAtt IAM.Outputs.EcsExecutioner

  Persistence:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${DeploymentBucket}/${release}/cloudformation/tetraforce/persistence.yaml'
      Parameters:
        environment: !Ref environment
        DeploymentBucket: !Ref DeploymentBucket
        release: !Ref release

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${DeploymentBucket}/${release}/cloudformation/tetraforce/api.yaml'
      Parameters:
        environment: !Ref environment
        DeploymentBucket: !Ref DeploymentBucket
        release: !Ref release
        LambdaRole: !GetAtt IAM.Outputs.LambdaRole
        EcsCluster: !Ref FargateCluster
        TaskDefinition: !GetAtt TaskDefinition.Outputs.TaskFamily
        ServerlistTable: !GetAtt Persistence.Outputs.ServerlistTable
        VpcId: !Ref VpcId
        TaskSecurityGroupId: !GetAtt TaskSecurityGroup.GroupId
        MaxServerCount: !Ref MaxServerCount